### ISSUE TITLE
Support basic authentication at the Nginx server.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/endpoint-monitor#3]
Allow endpoint-monitor to use a `.htpasswd` file, most likely set through a secret.

Verified manually that it works

**Comment by ddebrunner** [comment]
Online mechanism to generate `.htpasswd` entries: http://www.htaccesstools.com/htpasswd-generator/

Sample configuration: https://medium.com/@MicroPyramid/how-to-setup-http-password-authentication-with-nginx-38855fe5938

E.g.
```
location /streams/job/22/ {
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-Proto https ;
  proxy_set_header  X-Forwarded-For $remote_addr;
  proxy_set_header  X-Forwarded-Host $remote_addr;
  proxy_pass https://172.17.0.18:35578/;
  auth_basic "Job 22";
  auth_basic_user_file /opt/streams_job_configs/.htpasswd;
}
```

**Comment by joergboe** [comment]
We should support basic authentication in the inetserver operators.

**Comment by ddebrunner** [comment]
Working using http access, needs to have docs.

**Comment by ddebrunner** [comment]
Now documented.
