### ISSUE TITLE
SSL certificate and key provisioning

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/endpoint-monitor#30]
I'm still not sure if I understood the certificate provisioning for the communication between proxy and streams.inetserver correct.

In `/var/run/secrets/streams-endpoint-monitor/streams-certs/streams-certs/client.pfx`
Is the client key + certificate.

But where is the truststore for the server certitficate? Or is the client configured to trust all certificates?

**Comment by ddebrunner** [comment]
HTTPS support is still a work in progress, documentation & script to create keys are in progress

**Comment by ddebrunner** [comment]
Still a work in progress but there is now an example script that creates certificates: https://github.com/IBMStreams/endpoint-monitor/blob/master/scripts/build_jetty_certs.sh

Its end result is a k8s secret called `${NAME}-streams-certs` where `${NAME}` is the parameter to be passed to `oc new-app`.

The secret contains these elements:

* `client.pfx` - Client certificate & key used by Nginx server to connect to Jetty operators.
* `server.jks` - Java key store containing the server certificate for the Jetty operators
* `cacerts.jks` - Java trust store containing the client certificate trusted by the Jetty operators (contents from `client.pfx`)
* `server.pass` - Generated password for `server.jks` (and its key) and `cacerts.jks`.
* `client.pass` - Generated password for `client.pfx`

Note these certificates are for Niginx (the client) connecting to the Jetty server.

**Comment by ddebrunner** [comment]
Separately I have code is an SPL composite that wraps the inject primitive operator and sets up the key stores from the base 64 encoded versions in the Streams application configuration.

This means the SPL developer using the operators doesn't need to know about certs/passwords etc. E.g.:
```
stream<Json> Buses = Inject() {
param
      context: "buses";
      monitor: 'dan-em';
}
```

where `dan-em` is the value of `${NAME}`

**Comment by ddebrunner** [comment]
Now in README.md and details page:

https://github.com/IBMStreams/endpoint-monitor/blob/master/README.md#4-define-https-certificates
