### ISSUE TITLE
Signature check is incorrect

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/endpoint-monitor#49]
The signature check should compute the signature over request body as is.
The current implementation computes the the signature over a stringified JSON object, which is not identically to the request body.
E.g. the request body is:
{"item1":"xxxx","item2":"yyyy"}

the stringified request body is:
"{\"item1\":\"xxxx\",\"item2\":\"yyyy\"}"

But the sender computes the signature over the plain body.

**Comment by Karsten12** [comment]
I wrote this code according to the example auth code for segment given [here](https://segment.com/docs/destinations/webhooks/#authentication). It says Segment calculates the SHA1 digest using the 'the JSON-stringified body of the request' so why is it incorrect?

**Comment by joergboe** [comment]
Unfortunately hides the display of md the escape characters. What I mean is:
the stringified request body is:
"{\\"item1\\":\\"xxxx\\",\\"item2\\":\\"yyyy\\"}"
And this is definitely not what goes over the wire.
The signature must sign what goes over the wire and not the result of an specific implementation.

**Comment by rnostream** [comment]
There is a huge difference when using JSON.stringify() depending on the input.

`var str = '{"value":2 };`
`JSON.stringify(str);     // delivers string "{\"value\":2}"  with charlength 15 `
`str = {"value":2};`
`JSON.stringify(str);     // delivers {"value":2}    with charlength 11`


It is now the question what nginx will provide inside r.requestBody!!!!!!!!!!!!!!
If it is a string JSON.stringify delivers the content with start and end quotes and escaped inner quotes.
If it is a JS object JSON.stringify delivers plain JSON string , not escaped quotes and no start/end quotes.

Now it's the big question what both end of the communication think what type requestBody is to be seen.

I think on **Segment side**, as they fill the body with their values,  requestBody is a JS object (and JSON.stringify() is used correctly). 
On **endpoint_monitor.nginx side** the request body is not parsed by nginx into a JSON object (nginx doesn't care about the content of the body) .... thus it is a string .... and thus JSON.stringify has **not to be used** ... as in Jörgs patch.

The code snippet on Segments documentation site has a precondition to be valid: the 'content-type' was already checked to be JSON and the body was parsed into a JS object from JSON.

**Comment by Karsten12** [comment]
I understand, thanks for catching that mistake, and the explanation. @joergboe could you submit a new PR fixing this specific issue since #51 was n/a and closed

**Comment by joergboe** [comment]
To double check our findings I recorded a request from SWegment with X-Signature header and verified the signature with openssl.

Summary the signature is computed over the plain message body.

Here the details:
The recorded request:
---------------------
POST /InjectedStream/ports/output/0/inject HTTP/1.1
Accept-Encoding: gzip, deflate
Date: Fri, 25 Oct 2019 12:47:51 GMT
Accept-Encoding: identity
User-Agent: Segment.io/1.0
Ot-Tracer-TraceId: 2585a1c7624b7fd9
Ot-Tracer-SpanId: 33c63a680f61b5d
Ot-Tracer-Sampled: true
Host: iy7pnzafkref3x52.myfritz.net:8080
Content-Type: application/json
X-Signature: 76e3fd67a138664e9b83757ffe29ab2281156b60
Content-Length: 317

{"channel":"server","email":"test@example.org","event":"Test Event Name","messageId":"test-message-t6w6z","projectId":"qdEN5Kfn3e","properties":{"property1":1,"property2":"test","property3":true},"replay":true,"secret used":"password","timestamp":"2019-10-25T12:47:23.019Z","type":"track","userId":"test-user-g6i47c"}

Commands to verify the signature:
---------------------------------

$ dat2="{\"channel\":\"server\",\"email\":\"test@example.org\",\"event\":\"Test Event Name\",\"messageId\":\"test-message-t6w6z\",\"projectId\":\"qdEN5Kfn3e\",\"properties\":{\"property1\":1,\"property2\":\"test\",\"property3\":true},\"replay\":true,\"secret used\":\"password\",\"timestamp\":\"2019-10-25T12:47:23.019Z\",\"type\":\"track\",\"userId\":\"test-user-g6i47c\"}"

$ echo "$dat2"
{"channel":"server","email":"test@example.org","event":"Test Event Name","messageId":"test-message-t6w6z","projectId":"qdEN5Kfn3e","properties":{"property1":1,"property2":"test","property3":true},"replay":true,"secret used":"password","timestamp":"2019-10-25T12:47:23.019Z","type":"track","userId":"test-user-g6i47c"}

$ echo -n "$dat2" | openssl dgst -sha1 -hex -hmac password
(stdin)= 76e3fd67a138664e9b83757ffe29ab2281156b60

**Comment by Karsten12** [comment]
@joergboe your PR #58 is exactly the same as #51 which Dan closed bc it contained code to resolve #50 , which is not an issue. Ask requested by Dan, I will be documenting/describing in more detail how the signature check works with and without a signature-secret present. Can you submit a new PR addressing only the JSON.stringify issue?

**Comment by rnostream** [comment]
@ddebrunner @Karsten12 Please can you pull the signature check PR #62 as new test instances are set up with full feature set enabled (signature check and internal https) and thus the EM instance won't work as is. 
Regardless of the fact that deleting 'yyy-authentication' secret will switch of the signature check.

**Comment by ddebrunner** [comment]
Fixed by #62
