### ISSUE TITLE
Signature check should be disabled if signature secret is not available

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/endpoint-monitor#50]
We should implement a means to disable the signature check. Even in Segment Webhook, the signature is optional.

**Comment by ddebrunner** [comment]
There is a means to disable the check, don't set the property `signature-secret` in the authentication secret.

**Comment by ddebrunner** [comment]
> But the default is enabled with a non documented secret.
I'm not sure what this means.

**Comment by ddebrunner** [comment]
Closing as there is an existing mechanism to not have a signature check, we don't need to complicate configuration with multiple methods.
