### ISSUE TITLE
The signature check must be clearely documented

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/endpoint-monitor#54]

**Comment by ddebrunner** [comment]
@Karsten12 Can you create a .md file describing how to configure and use the signature check for POST etc that can be linked from the main README.md

**Comment by Karsten12** [comment]
@joergboe I created a .md file in #63 that describes in detail how the signature verification works. You likely know more about endpoint-monitor than I do so if I made a mistake in my explanation, please let me know and I'll fix it asap.

**Comment by joergboe** [comment]
What I mean is a description from the user point of view. 
* How can I enable/disable the signature check 
* What does the signature check do. What kind of methods are checked against the signature (Methods with body?)
* What kind of signature is required from the sender (sha1 hmac over the body)

**Comment by Karsten12** [comment]
Ok, I will consult with Dan about this and if need be, update my PR. But just off the top of my head, I don't believe signature check is of concern to the user, so the user cannot enable/disable it, but I could be wrong

**Comment by ddebrunner** [comment]
@Karsten12 Please create doc files in the newly added `docs` folder.

**Comment by ddebrunner** [comment]
cf https://github.com/IBMStreams/endpoint-monitor/blob/master/README.md#4-define-https-certificates

**Comment by ddebrunner** [comment]
Done.

**Comment by ddebrunner** [comment]
Actually, still need an example on signing requests.

**Comment by joergboe** [comment]
https://github.com/IBMStreams/endpoint-monitor/blob/develop/docs/signature_auth.md

To Sign a request (file dat0.txt contains the request body):

curl -k --header 'Content-Type: application/json' --header "X-Signature: $(openssl dgst -sha1 -hex -hmac password dat0.txt | cut -d ' ' -f 2 )" --request POST --data @dat0.txt  <url>
