### ISSUE TITLE
Application configuration not accessible by non-admin user

### ISSUE THREAD

**Issue by schubon** [IBMStreams/endpoint-monitor#64]
On the current CP4D Blitz test machine the application configuration for endpoint-monitor is not accessible by a non-admin user, so a call to endpoint.inject(...) fails during initialization.

**Comment by ddebrunner** [comment]
@schubon You need to use a Streams user that creates a job config that is visible to the Streams user the Streams job is running as.

What Streams users did you configure for the endpoint monitor and the Streams job?

**Comment by schubon** [comment]
Okay ... probably just my state of confusion again (sorry for that):
First I was using "stest03", which did not have access to the application configuration for the configured endpoint and which we saw using the admin account.
So is this just a matter of granting access to the existing application configuration or will we need to go full-circle following the instructions in the ReadMe and create user specific application configs, certificates, etc. (with own STREAMS_USER / STREAMS_PASSWORD)?

**Comment by ddebrunner** [comment]
@schubon Yeah, could probably do with some more explicit instructions on a typical setup, which to my mind would be:

- endpoint-monitor is monitoring jobs in a single job group
- Only a single Streams user has the right to submit jobs to that group.
- One of these users as the Streams user for endpoint-monitor:
    -  The same job submitter Streams user
    - A Streams user that cannot submit jobs,  but can monitor them in the job group.

**Comment by ddebrunner** [comment]
@schubon You can also just modify the secret containing the Streams user, it should restart the endpoint-monitor pod and then use the new user.

**Comment by joergboe** [comment]
s README.md Step1 'Define Streams user' and it should work
