### ISSUE TITLE
Invalid location modifier "~^" in nginx job configuration

### ISSUE THREAD

**Issue by schubon** [IBMStreams/endpoint-monitor#69]
We were playing around on the Blitz machine (ngb8) and wanted to try if with the merged signature patch we get to exchanging messages yet. So we triggered a new build for "streams-endpoint-monitor".

Unfortunately, we didn't get far, as we ran into a new error:
Invalid location modifier "~^" in nginx job configuration

**Comment by ddebrunner** [comment]
Fixed by 0981aba5a8ae6ee0e9a677c2f4d70f93e8b3d494
