### ISSUE TITLE
Support signature verification at the nginx entry

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/endpoint-monitor#8]
Style of signing: https://forum.level1techs.com/t/signing-http-requests-to-make-sure-that-the-client-is-not-an-attacker-or-bot/111821

Sample use for Segment. https://segment.com/docs/destinations/webhooks/#authentication

**Comment by ddebrunner** [comment]
@Karsten12 is looking at this mechanism to verify signatures. https://www.nginx.com/blog/introduction-nginscript/

**Comment by joergboe** [comment]
We should support signature verification in the inetserver operators.

**Comment by joergboe** [comment]
Or better support this in the ineternetserver operators. End to End authentication makes more sense.

**Comment by ddebrunner** [comment]
@joergboe Could you expand more on why handling authentication at the nginx layer is not sufficient. 

We can take advantage of the multiple styles of authentication supported by an existing standard network server, rather than having to implement them all at the Jetty operator level, increasing the complexity of the operators (more parameters, more combinations etc.)

**Comment by ddebrunner** [comment]
Done.
